name: Lint and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Linting
        run: |
          yarn lint:ci

  build and test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Yarn Install
        run: |
          yarn install --silent --production=false
      
      - name: Yarn Build
        run: |
          yarn build
      - name: Jest
        run: |
          yarn jest
